### ISSUE TITLE
"TypeError: input.trim is not a function"

### ISSUE THREAD

**Issue by ad-m** [osmoscraft/osmosfeed#56]
I have attempt to use your tool https://github.com/ad-m/feed-reader on with following configuration:

```
# cacheUrl: https://GITHUB_USERNAME.github.io/REPO_NAME/cache.json
sources:
  - href: https://github.com/osmoscraft/osmosfeed/releases.atom # Get new feature announcement via this feed
  - href: https://cloudblog.withgoogle.com/rss/
  - href: https://news.ycombinator.com/rss
  - href: https://aws.amazon.com/blogs/aws/feed/
  - href: https://lwn.net/headlines/newrss
  - href: http://feeds.feedburner.com/HighScalability
  - href: https://www.phoronix.com/rss.php
```

I received following failure build log:

```
2021-09-11T00:23:40.8850901Z Found online and idle hosted runner in the current repository's organization account that matches the required labels: 'ubuntu-latest'
2021-09-11T00:23:40.9316674Z Waiting for a Hosted runner in the 'organization' to pick this job...
2021-09-11T00:23:41.2130944Z Job is waiting for a hosted runner to come online.
2021-09-11T00:23:44.2468374Z Job is about to start running on the hosted runner: GitHub Actions 2 (hosted)
2021-09-11T00:23:46.2853260Z Current runner version: '2.281.1'
2021-09-11T00:23:46.2879908Z ##[group]Operating System
2021-09-11T00:23:46.2881100Z Ubuntu
2021-09-11T00:23:46.2881640Z 20.04.3
2021-09-11T00:23:46.2882130Z LTS
2021-09-11T00:23:46.2882692Z ##[endgroup]
2021-09-11T00:23:46.2883336Z ##[group]Virtual Environment
2021-09-11T00:23:46.2884105Z Environment: ubuntu-20.04
2021-09-11T00:23:46.2884711Z Version: 20210906.1
2021-09-11T00:23:46.2886143Z Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210906.1/images/linux/Ubuntu2004-README.md
2021-09-11T00:23:46.2887715Z Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210906.1
2021-09-11T00:23:46.2888724Z ##[endgroup]
2021-09-11T00:23:46.2889458Z ##[group]Virtual Environment Provisioner
2021-09-11T00:23:46.2890176Z 1.0.0.0-master-20210816-1
2021-09-11T00:23:46.2890810Z ##[endgroup]
2021-09-11T00:23:46.2893073Z ##[group]GITHUB_TOKEN Permissions
2021-09-11T00:23:46.2894533Z Actions: write
2021-09-11T00:23:46.2895121Z Checks: write
2021-09-11T00:23:46.2895710Z Contents: write
2021-09-11T00:23:46.2896270Z Deployments: write
2021-09-11T00:23:46.2896909Z Discussions: write
2021-09-11T00:23:46.2897442Z Issues: write
2021-09-11T00:23:46.2898167Z Metadata: read
2021-09-11T00:23:46.2898756Z Packages: write
2021-09-11T00:23:46.2899427Z PullRequests: write
2021-09-11T00:23:46.2900189Z RepositoryProjects: write
2021-09-11T00:23:46.2900890Z SecurityEvents: write
2021-09-11T00:23:46.2901568Z Statuses: write
2021-09-11T00:23:46.2902216Z ##[endgroup]
2021-09-11T00:23:46.2905704Z Prepare workflow directory
2021-09-11T00:23:46.3530115Z Prepare all required actions
2021-09-11T00:23:46.3540277Z Getting action download info
2021-09-11T00:23:46.5605717Z Download action repository 'actions/checkout@v2' (SHA:5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f)
2021-09-11T00:23:48.2931904Z Download action repository 'actions/setup-node@v2.1.4' (SHA:c46424eee26de4078d34105d3de3cc4992202b1e)
2021-09-11T00:23:48.5192327Z Download action repository 'peaceiris/actions-gh-pages@v3' (SHA:068dc23d9710f1ba62e86896f84735d869951305)
2021-09-11T00:23:48.8938672Z ##[group]Run actions/checkout@v2
2021-09-11T00:23:48.8939240Z with:
2021-09-11T00:23:48.8939642Z   repository: ad-m/feed-reader
2021-09-11T00:23:48.8940477Z   token: ***
2021-09-11T00:23:48.8940844Z   ssh-strict: true
2021-09-11T00:23:48.8941288Z   persist-credentials: true
2021-09-11T00:23:48.8941730Z   clean: true
2021-09-11T00:23:48.8942078Z   fetch-depth: 1
2021-09-11T00:23:48.8942436Z   lfs: false
2021-09-11T00:23:48.8942781Z   submodules: false
2021-09-11T00:23:48.8943154Z ##[endgroup]
2021-09-11T00:23:49.4990046Z Syncing repository: ad-m/feed-reader
2021-09-11T00:23:49.5022920Z ##[group]Getting Git version info
2021-09-11T00:23:49.5024396Z Working directory is '/home/runner/work/feed-reader/feed-reader'
2021-09-11T00:23:49.5032462Z [command]/usr/bin/git version
2021-09-11T00:23:49.5033055Z git version 2.33.0
2021-09-11T00:23:49.5035289Z ##[endgroup]
2021-09-11T00:23:49.5036141Z Deleting the contents of '/home/runner/work/feed-reader/feed-reader'
2021-09-11T00:23:49.5038396Z ##[group]Initializing the repository
2021-09-11T00:23:49.5039773Z [command]/usr/bin/git init /home/runner/work/feed-reader/feed-reader
2021-09-11T00:23:49.5041542Z hint: Using 'master' as the name for the initial branch. This default branch name
2021-09-11T00:23:49.5055933Z hint: is subject to change. To configure the initial branch name to use in all
2021-09-11T00:23:49.5072225Z hint: of your new repositories, which will suppress this warning, call:
2021-09-11T00:23:49.5073102Z hint: 
2021-09-11T00:23:49.5074163Z hint: 	git config --global init.defaultBranch <name>
2021-09-11T00:23:49.5074925Z hint: 
2021-09-11T00:23:49.5075936Z hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
2021-09-11T00:23:49.5077062Z hint: 'development'. The just-created branch can be renamed via this command:
2021-09-11T00:23:49.5077804Z hint: 
2021-09-11T00:23:49.5078516Z hint: 	git branch -m <name>
2021-09-11T00:23:49.5079575Z Initialized empty Git repository in /home/runner/work/feed-reader/feed-reader/.git/
2021-09-11T00:23:49.5081192Z [command]/usr/bin/git remote add origin https://github.com/ad-m/feed-reader
2021-09-11T00:23:49.5082607Z ##[endgroup]
2021-09-11T00:23:49.5083909Z ##[group]Disabling automatic garbage collection
2021-09-11T00:23:49.5085101Z [command]/usr/bin/git config --local gc.auto 0
2021-09-11T00:23:49.5086297Z ##[endgroup]
2021-09-11T00:23:49.5089185Z ##[group]Setting up auth
2021-09-11T00:23:49.5090222Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2021-09-11T00:23:49.5092011Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2021-09-11T00:23:49.5093803Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2021-09-11T00:23:49.5095875Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2021-09-11T00:23:49.5097882Z [command]/usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
2021-09-11T00:23:49.5099425Z ##[endgroup]
2021-09-11T00:23:49.5100629Z ##[group]Fetching the repository
2021-09-11T00:23:49.5102796Z [command]/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +76fe50020339cca181136b57965f229c648c9d32:refs/remotes/origin/main
2021-09-11T00:23:49.5104178Z remote: Enumerating objects: 9, done.        
2021-09-11T00:23:49.5104877Z remote: Counting objects:  11% (1/9)        
2021-09-11T00:23:49.5105571Z remote: Counting objects:  22% (2/9)        
2021-09-11T00:23:49.5106223Z remote: Counting objects:  33% (3/9)        
2021-09-11T00:23:49.5107636Z remote: Counting objects:  44% (4/9)        
2021-09-11T00:23:49.5108332Z remote: Counting objects:  55% (5/9)        
2021-09-11T00:23:49.5109265Z remote: Counting objects:  66% (6/9)        
2021-09-11T00:23:49.5110018Z remote: Counting objects:  77% (7/9)        
2021-09-11T00:23:49.5110699Z remote: Counting objects:  88% (8/9)        
2021-09-11T00:23:49.5111423Z remote: Counting objects: 100% (9/9)        
2021-09-11T00:23:49.5112133Z remote: Counting objects: 100% (9/9), done.        
2021-09-11T00:23:49.5112890Z remote: Compressing objects:  16% (1/6)        
2021-09-11T00:23:49.5113636Z remote: Compressing objects:  33% (2/6)        
2021-09-11T00:23:49.5114361Z remote: Compressing objects:  50% (3/6)        
2021-09-11T00:23:49.5115101Z remote: Compressing objects:  66% (4/6)        
2021-09-11T00:23:49.5115843Z remote: Compressing objects:  83% (5/6)        
2021-09-11T00:23:49.5116563Z remote: Compressing objects: 100% (6/6)        
2021-09-11T00:23:49.5117329Z remote: Compressing objects: 100% (6/6), done.        
2021-09-11T00:23:49.5118633Z remote: Total 9 (delta 0), reused 4 (delta 0), pack-reused 0        
2021-09-11T00:23:49.5119685Z From https://github.com/ad-m/feed-reader
2021-09-11T00:23:49.5120793Z  * [new ref]         76fe50020339cca181136b57965f229c648c9d32 -> origin/main
2021-09-11T00:23:49.5122076Z ##[endgroup]
2021-09-11T00:23:49.5123214Z ##[group]Determining the checkout info
2021-09-11T00:23:49.5124598Z ##[endgroup]
2021-09-11T00:23:49.5125892Z ##[group]Checking out the ref
2021-09-11T00:23:49.5126925Z [command]/usr/bin/git checkout --progress --force -B main refs/remotes/origin/main
2021-09-11T00:23:49.5127899Z Switched to a new branch 'main'
2021-09-11T00:23:49.5128812Z Branch 'main' set up to track remote branch 'main' from 'origin'.
2021-09-11T00:23:49.5129983Z ##[endgroup]
2021-09-11T00:23:49.5130747Z [command]/usr/bin/git log -1 --format='%H'
2021-09-11T00:23:49.5131662Z '76fe50020339cca181136b57965f229c648c9d32'
2021-09-11T00:23:49.5268462Z ##[group]Run actions/setup-node@v2.1.4
2021-09-11T00:23:49.5268961Z with:
2021-09-11T00:23:49.5269351Z   node-version: 16
2021-09-11T00:23:49.5269809Z   always-auth: false
2021-09-11T00:23:49.5270395Z   check-latest: false
2021-09-11T00:23:49.5271312Z   token: ***
2021-09-11T00:23:49.5271709Z ##[endgroup]
2021-09-11T00:23:50.2943322Z Attempting to download 16...
2021-09-11T00:23:50.2949518Z Acquiring 16.9.0 - x64 from https://github.com/actions/node-versions/releases/download/16.9.0-1212244385/node-16.9.0-linux-x64.tar.gz
2021-09-11T00:23:50.4882386Z Extracting ...
2021-09-11T00:23:50.5025705Z [command]/usr/bin/tar xz --strip 1 --warning=no-unknown-keyword -C /home/runner/work/_temp/9d19923f-26f9-47a8-a2b7-12b6fb4ec215 -f /home/runner/work/_temp/bb417eb5-f2c4-41cd-a351-f68a20c64d86
2021-09-11T00:23:51.4086368Z Adding to the cache ...
2021-09-11T00:23:52.3825450Z Done
2021-09-11T00:23:52.3970614Z ##[group]Run npm i
2021-09-11T00:23:52.3971116Z [36;1mnpm i[0m
2021-09-11T00:23:52.4014889Z shell: /usr/bin/bash -e {0}
2021-09-11T00:23:52.4015378Z ##[endgroup]
2021-09-11T00:23:54.7269530Z 
2021-09-11T00:23:54.7272518Z added 32 packages, and audited 33 packages in 2s
2021-09-11T00:23:54.7273750Z 
2021-09-11T00:23:54.7274818Z 12 packages are looking for funding
2021-09-11T00:23:54.7275984Z   run `npm fund` for details
2021-09-11T00:23:54.7278876Z 
2021-09-11T00:23:54.7279813Z found 0 vulnerabilities
2021-09-11T00:23:54.7412883Z ##[group]Run npm run build
2021-09-11T00:23:54.7413407Z [36;1mnpm run build[0m
2021-09-11T00:23:54.7452731Z shell: /usr/bin/bash -e {0}
2021-09-11T00:23:54.7453182Z ##[endgroup]
2021-09-11T00:23:55.0395132Z 
2021-09-11T00:23:55.0397393Z > osmosfeed-template@1.0.0 build
2021-09-11T00:23:55.0398566Z > osmosfeed
2021-09-11T00:23:55.0399099Z 
2021-09-11T00:23:55.1592967Z [main] Starting build using cli version 1.11.0
2021-09-11T00:23:55.1610660Z [system-file] Config: /home/runner/work/feed-reader/feed-reader/osmosfeed.yaml
2021-09-11T00:23:55.1619389Z [system-file] Local cache: undefined
2021-09-11T00:23:55.1624282Z [system-file] Template: /home/runner/work/feed-reader/feed-reader/node_modules/@osmoscraft/osmosfeed/bin/system-templates/index.hbs
2021-09-11T00:23:55.1641521Z [system-file] System static: /home/runner/work/feed-reader/feed-reader/node_modules/@osmoscraft/osmosfeed/bin/system-static/favicon.ico
2021-09-11T00:23:55.1647538Z [system-file] System template static: /home/runner/work/feed-reader/feed-reader/node_modules/@osmoscraft/osmosfeed/bin/system-static/index.css
2021-09-11T00:23:55.1650924Z [system-file] System template static: /home/runner/work/feed-reader/feed-reader/node_modules/@osmoscraft/osmosfeed/bin/system-static/index.js
2021-09-11T00:23:55.1719554Z [load-config] Effective config:  {
2021-09-11T00:23:55.1720413Z   sources: [
2021-09-11T00:23:55.1721613Z     { href: 'https://github.com/osmoscraft/osmosfeed/releases.atom' },
2021-09-11T00:23:55.1723023Z     { href: 'https://cloudblog.withgoogle.com/rss/' },
2021-09-11T00:23:55.1724352Z     { href: 'https://news.ycombinator.com/rss' },
2021-09-11T00:23:55.1725777Z     { href: 'https://aws.amazon.com/blogs/aws/feed/' },
2021-09-11T00:23:55.1726921Z     { href: 'https://lwn.net/headlines/newrss' },
2021-09-11T00:23:55.1727971Z     { href: 'http://feeds.feedburner.com/HighScalability' },
2021-09-11T00:23:55.1729111Z     { href: 'https://www.phoronix.com/rss.php' }
2021-09-11T00:23:55.1729744Z   ],
2021-09-11T00:23:55.1730194Z   cacheUrl: null,
2021-09-11T00:23:55.1730737Z   cacheMaxDays: 30,
2021-09-11T00:23:55.1731628Z   siteTitle: 'osmos::feed'
2021-09-11T00:23:55.1732185Z }
2021-09-11T00:23:55.1894024Z [get-cache] Use empty cache
2021-09-11T00:23:55.4504554Z [enrich] 0.27s |   0 cached |   1 new | http://feeds.feedburner.com/HighScalability
2021-09-11T00:23:55.7816607Z /home/runner/work/feed-reader/feed-reader/node_modules/@osmoscraft/osmosfeed/bin/main.js:31625
2021-09-11T00:23:55.7817697Z   const trimmed = input == null ? void 0 : input.trim();
2021-09-11T00:23:55.7818321Z                                                  ^
2021-09-11T00:23:55.7818629Z 
2021-09-11T00:23:55.7819240Z TypeError: input.trim is not a function
2021-09-11T00:23:55.7820745Z     at getNonEmptyStringOrNull (/home/runner/work/feed-reader/feed-reader/node_modules/@osmoscraft/osmosfeed/bin/main.js:31625:50)
2021-09-11T00:23:55.7822699Z     at /home/runner/work/feed-reader/feed-reader/node_modules/@osmoscraft/osmosfeed/bin/main.js:31756:16
2021-09-11T00:23:55.7823604Z     at Array.map (<anonymous>)
2021-09-11T00:23:55.7824846Z     at normalizeFeed (/home/runner/work/feed-reader/feed-reader/node_modules/@osmoscraft/osmosfeed/bin/main.js:31754:23)
2021-09-11T00:23:55.7826709Z     at enrichInternal (/home/runner/work/feed-reader/feed-reader/node_modules/@osmoscraft/osmosfeed/bin/main.js:31669:16)
2021-09-11T00:23:55.7828150Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2021-09-11T00:23:55.7829080Z     at async Promise.all (index 1)
2021-09-11T00:23:55.7830419Z     at async run (/home/runner/work/feed-reader/feed-reader/node_modules/@osmoscraft/osmosfeed/bin/main.js:31875:27)
2021-09-11T00:23:55.8214108Z ##[error]Process completed with exit code 1.
2021-09-11T00:23:55.8321922Z Post job cleanup.
2021-09-11T00:23:55.9366195Z [command]/usr/bin/git version
2021-09-11T00:23:55.9411282Z git version 2.33.0
2021-09-11T00:23:55.9456090Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2021-09-11T00:23:55.9491890Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2021-09-11T00:23:55.9722201Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2021-09-11T00:23:55.9738000Z http.https://github.com/.extraheader
2021-09-11T00:23:55.9752634Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2021-09-11T00:23:55.9777290Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2021-09-11T00:23:56.0222703Z Cleaning up orphan processes
```

Any idea why it fails?

**Comment by ad-m** [comment]
I have determined that feed https://cloudblog.withgoogle.com/rss/ make it fail.

**Comment by chuanqisun** [comment]
Thanks for the report! It turns out the google cloud blog uses RSS 2.0 format but the `author` field is using Atom namespace with nested child elements. The current implementation expects the author field to be plaintext so it crashed when there are child elements. I'll publish a quick fix shortly.

**Comment by chuanqisun** [comment]
v1.11.1 contains the fix. Please try a rebuild. It should work with Google Cloud Blog feed now.
![image](https://user-images.githubusercontent.com/1895289/133562152-2c7665e7-e8df-4f52-8b26-187903a0aa1a.png)
